spring:
  application:
    name: meetime-test-case
  security:
    oauth2:
      client:
        registration:
          hubspot:
            client-id: ${HUBSPOT_CLIENT_ID}
            client-secret: ${HUBSPOT_CLIENT_SECRET}
            client-name: HubSpot
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost
            scope: oauth,crm.objects.contacts.read
        provider:
          hubspot:
            authorization-uri: https://app.hubspot.com/oauth/authorize
            token-uri: https://api.hubapi.com/oauth/v1/token
            user-info-uri: https://api.hubapi.com/oauth/v1/userinfo
            user-name-attribute: user